### ISSUE TITLE
Says it unfollowed everyone but it didn't

### ISSUE THREAD

**Issue by revanthrr** [tashfeenahmed/Twitter-Unfollower-Bot#1]
I ran it and left it for a couple of minutes, it unfollowed like 300 people and said that i have unfollowed everyone that doesn't follow me back, but i logged into tweepi account and there are still many non followers that the script didn't unfollow :\ is this a limit? sorry, i'm new to coding btw and the account i tried on has 6000 followers and following 3000 people.

**Comment by tashfeenahmed** [comment]
The message that 'You have unfollowed everyone who was not following you back' appears when the process finishes. In your case, most probably, you had reached twitter's daily limit.

But I'm glad you implemented this code and tried it ^_^

**Comment by revanthrr** [comment]
Thank you, and you're right it was just the limit, i had to run it in different times, but still gets the job done! thanks again for the code :)

**Comment by tashfeenahmed** [comment]
Perfect!
